# Generated by Django 5.1.5 on 2025-02-10 17:51
from __future__ import annotations

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_posts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(
                null=True,
                upload_to='assets/portfolio_backend.apps.api.models.comments'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(
                null=True,
                upload_to='assets/portfolio_backend.apps.api.models.posts'),
        ),
    ]
