version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres_dev
    environment:
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_password
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
   driver: local
